import { Link } from "react-router";

type PolicyKind = "privacy" | "terms" | "returns" | "shipping";

const content: Record<PolicyKind, { title: string; intro: string; sections: Array<[string, string]> }> = {
  privacy: { title: "Privacy Policy", intro: "This draft explains how MarketVerse handles information used to provide marketplace, account, order, payment, and support features.", sections: [["Information used by the platform", "MarketVerse may process account, contact, delivery, order, seller, and support information needed to operate the platform."], ["Payments", "Online payment processing is handled through SSLCommerz. MarketVerse does not request payment information during seller registration."], ["Use of information", "Information is used for authentication, order fulfillment, customer support, seller operations, notifications, and platform improvements."], ["Contact", "For privacy questions, contact support@marketverse.com.bd or call 01711654706."]] },
  terms: { title: "Terms & Conditions", intro: "These draft terms govern use of the MarketVerse multi-vendor marketplace.", sections: [["Accounts", "Users are responsible for providing accurate information and protecting their account credentials."], ["Customers and orders", "Customers are responsible for reviewing product information, delivery details, and order information before placing an order."], ["Sellers and listings", "Sellers are responsible for accurate listings, inventory, pricing, fulfillment, customer communication, and compliance with applicable requirements."], ["Payment and delivery", "MarketVerse supports SSLCommerz online payment and Cash on Delivery where available. Delivery, returns, and refunds may depend on the order and seller."], ["Prohibited activity", "Users must not misuse the platform, submit unlawful content, interfere with platform operation, or attempt unauthorized access."], ["Changes and contact", "These draft terms may be updated as the platform evolves. Contact support@marketverse.com.bd with questions."]] },
  returns: { title: "Return & Refund Policy", intro: "Project policy draft: final return rules may depend on product type, seller terms, and the condition of the delivered item.", sections: [["Eligibility", "Customers should contact MarketVerse support promptly when an item is damaged, incorrect, materially different from its listing, or otherwise eligible under the applicable seller terms."], ["Product condition", "Items should be kept unused where possible and returned with original packaging, accessories, and proof of order when requested."], ["Request process", "Contact support with the order number, issue description, and clear photos where relevant. The seller and MarketVerse support team may review the request."], ["Refunds", "Approved refunds are handled according to the payment method and the outcome of the return review. SSLCommerz payments may be returned through the applicable payment process; Cash on Delivery refunds require support instructions."], ["Non-returnable items", "Certain personal-use, perishable, customized, or hygiene-sensitive products may not be returnable unless damaged or incorrect."], ["Responsibilities", "Sellers should provide accurate listings and resolve valid issues. Customers should inspect deliveries and submit complete, truthful information."]] },
  shipping: { title: "Shipping Information", intro: "Shipping availability, charges, delivery timing, and courier handling can vary by seller, product, destination, and order.", sections: [["Delivery details", "Customers should provide a complete Bangladesh delivery address and reachable phone number at checkout."], ["Charges and timing", "Applicable delivery charges and estimated timing are shown or calculated during checkout where available. Remote or outside-Dhaka delivery may differ."], ["Order tracking", "Use My Orders to review available order status and tracking information."], ["Delivery issues", "Contact MarketVerse support promptly for delayed, damaged, incomplete, or incorrectly delivered orders."], ["Seller responsibility", "Sellers are responsible for preparing accurate orders and handing them to the supported delivery process."]] },
};

export default function PolicyPage({ kind }: { kind: PolicyKind }) {
  const page = content[kind];
  return <div className="mx-auto w-full max-w-4xl px-4 py-12 sm:px-6 lg:py-16"><p className="text-xs font-bold uppercase tracking-[0.18em] text-indigo-600 dark:text-indigo-400">MarketVerse policy draft</p><h1 className="mt-3 text-4xl font-black tracking-tight text-slate-900 dark:text-white">{page.title}</h1><p className="mt-4 text-base leading-7 text-slate-600 dark:text-slate-400">{page.intro}</p><div className="mt-10 space-y-6">{page.sections.map(([heading, body]) => <section key={heading} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-700 dark:bg-slate-900"><h2 className="text-lg font-bold text-slate-900 dark:text-white">{heading}</h2><p className="mt-2 text-sm leading-7 text-slate-600 dark:text-slate-400">{body}</p></section>)}</div><p className="mt-8 text-sm text-slate-500 dark:text-slate-400">Need help? <Link to="/contact" className="font-semibold text-indigo-600 hover:underline dark:text-indigo-400">Contact MarketVerse support</Link>.</p></div>;
}
