import { execFileSync, spawn } from "node:child_process";
import { randomBytes } from "node:crypto";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

const root = path.resolve(import.meta.dirname, "..");
const envPath = path.join(root, ".env");
const npmCommand = process.platform === "win32" ? "npm.cmd" : "npm";

function run(command, args, options = {}) {
  console.log(`\n> ${command} ${args.join(" ")}`);
  execFileSync(command, args, { cwd: root, stdio: "inherit", ...options });
}

function commandExists(command) {
  try {
    execFileSync(process.platform === "win32" ? "where.exe" : "which", [command], {
      stdio: "ignore",
    });
    return true;
  } catch {
    return false;
  }
}

function parseEnv(contents) {
  return Object.fromEntries(
    contents
      .split(/\r?\n/)
      .map((line) => line.match(/^\s*([A-Z][A-Z0-9_]*)\s*=\s*(.*)\s*$/))
      .filter(Boolean)
      .map(([, key, value]) => [key, value.replace(/^['"]|['"]$/g, "")])
  );
}

function createLocalEnv() {
  if (existsSync(envPath)) {
    return parseEnv(readFileSync(envPath, "utf8"));
  }

  const env = {
    NODE_ENV: "development",
    PORT: "5173",
    DATABASE_URL: "mysql://root:password@127.0.0.1:3306/ecommerce_db",
    APP_ID: "marketverse-local",
    APP_SECRET: randomBytes(32).toString("hex"),
    CORS_ORIGIN: "*",
    OWNER_UNION_ID: "local:01700000006",
    OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
    KIMI_AUTH_URL: "",
    KIMI_OPEN_URL: "",
    VITE_KIMI_AUTH_URL: "",
    VITE_APP_ID: "",
    GOOGLE_CLIENT_ID: "",
    GOOGLE_CLIENT_SECRET: "",
    SMTP_HOST: "smtp.gmail.com",
    SMTP_PORT: "465",
    SMTP_SECURE: "true",
    SMTP_USER: "",
    SMTP_PASS: "",
    SMTP_FROM: "",
    SSLCOMMERZ_STORE_ID: "testbox",
    SSLCOMMERZ_STORE_PASSWORD: "qwerty",
    SSLCOMMERZ_IS_LIVE: "false",
  };

  const lines = [
    "# Generated by npm run setup. This file is local and ignored by git.",
    ...Object.entries(env).map(([key, value]) => `${key}=${value}`),
    "",
  ];
  writeFileSync(envPath, lines.join("\n"), { encoding: "utf8", flag: "wx" });
  console.log("Created .env with safe local defaults.");
  return env;
}

async function waitForDatabase(databaseUrl) {
  const { createConnection } = await import("mysql2/promise");
  const deadline = Date.now() + 60_000;
  let lastError;

  while (Date.now() < deadline) {
    try {
      const connection = await createConnection(databaseUrl);
      await connection.query("SELECT 1");
      await connection.end();
      console.log("MySQL is ready.");
      return;
    } catch (error) {
      lastError = error;
      await new Promise((resolve) => setTimeout(resolve, 1000));
    }
  }

  throw new Error(`MySQL was not ready after 60 seconds: ${lastError?.message || "unknown error"}`);
}

function prepareOllama() {
  if (!commandExists("ollama")) {
    console.warn("Ollama was not found. Local AI models were not installed; install Ollama and rerun npm run setup.");
    return;
  }

  for (const model of ["qwen2.5:3b-instruct", "nomic-embed-text"]) {
    try {
      run("ollama", ["pull", model]);
    } catch (error) {
      console.warn(`Could not pull Ollama model ${model}: ${error.message}`);
    }
  }
}

async function main() {
  process.chdir(root);
  console.log("MarketVerse setup");
  console.log(`Project root: ${root}`);

  if (!commandExists("node")) {
    throw new Error("Node.js 20 or newer is required. Install the current Node.js LTS release and run npm run setup again.");
  }

  const majorNodeVersion = Number(process.versions.node.split(".")[0]);
  if (majorNodeVersion < 20) {
    throw new Error(`Node.js 20 or newer is required. Detected ${process.versions.node}.`);
  }

  const env = createLocalEnv();
  run(npmCommand, ["ci"]);

  if (commandExists("docker")) {
    try {
      run("docker", ["compose", "up", "-d", "db"]);
      await waitForDatabase(env.DATABASE_URL);
    } catch (error) {
      console.warn(`Docker database setup was skipped: ${error.message}`);
    }
  } else {
    console.warn("Docker was not found. A MySQL 8 server must already be running at DATABASE_URL.");
  }

  prepareOllama();

  try {
    run(npmCommand, ["run", "db:seed"]);
  } catch (error) {
    throw new Error("Database seeding failed. Start MySQL or Docker, verify DATABASE_URL in .env, then run npm run db:seed.", { cause: error });
  }

  if (!env.OPENAI_API_KEY) {
    console.warn("OPENAI_API_KEY is empty. Core commerce works, but API-backed AI features will use their fallbacks.");
  }

  console.log("\nSetup complete. Starting MarketVerse at http://localhost:5173");
  const child = spawn(npmCommand, ["run", "dev"], { cwd: root, stdio: "inherit", env: process.env });
  process.on("SIGINT", () => child.kill("SIGINT"));
  process.on("SIGTERM", () => child.kill("SIGTERM"));
  child.on("exit", (code) => process.exit(code ?? 0));
}

main().catch((error) => {
  console.error(`\nSetup failed: ${error.message}`);
  process.exit(1);
});
